image: ...

stages:
  - build

build:
  stage: build
  script:
    - CI=false
    - docker-compose -f deploy/docker-compose.yaml up --force-recreate --build -d
  only:
    - master
  tags:
    - gR1

